# Generated by Django 2.0.5 on 2018-06-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='numberOfCopiesSold',
            field=models.BigIntegerField(default=0),
        ),
    ]
